###
POST http://localhost:5000/api/v1/user
Content-Type: application/json; charset=utf-8

{
    "name": "Simon Paul",
    "email": "simon@paul.com",
    "password": "1234",
    "retype_password": "1234"
}
###
