version: "3"

services:
  dentbud_backend_rasa:
    build: .
    restart: always
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\" -p 8080"
    ports:
      - "5006:8080"
    public: true
    env_file:
      - .env

endpoints:
  - path: /
    service: dentbud_backend_rasa
    port: 5006